### PR TITLE
Add custom RPC option in preferences

### PR DESCRIPTION
**Pull request by michaelstokesdev**
Added the ability to use a custom RPC client ID so users can customise the look of their status.
image

### CODE REVIEW

**Comment by sll552** [comment]
Thanks for your contribution, I have a few things I would like to see changed before this can get merged.

I see the motivation around this but I do not want to confuse "normal" users with this setting. So I would like to suggest that this setting is somehow "hidden", if thats through some sort of collapsed "advanced" settings dialog or maybe only changeable through the settings file. 
With this in place users who still want to use a different discord appID can do so and no one else will be bothered or confused with a setting that is not clear to someone who is not a developer. Also a small section in the ReadMe would be nice how this can be changed and whats needed (Discord App in Dev portal and the image keys).

**Comment by michaelstokesdev** [comment]
Sounds good. I'll work on making the option hidden and I'll add a little section in the readme.

**Comment by heyekto** [comment]
@michaelstokesdev what is this?

**Comment by michaelstokesdev** [comment]
Apologies. Pretty sure I've pushed the wrong version there, hence the errors. I'll get it fixed and pushed asap.

**Comment by michaelstokesdev** [comment]
@ekto it's an additional setting that will allow users more customisation options. Once I have it working and merged I'll write a section in the README to explain how to use it.

**Comment by michaelstokesdev** [comment]
Just going to close this pull request for now, do a little rework of my changes, then I'll open a new one once I sort everything out.

**Pull request closed without merging**
